server:
  port: 8001

spring:
  application:
    name: xywm-back
  datasource:
    url: jdbc:mysql://localhost:3306/top_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password:  123456
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000

  redis:
    jedis:
      pool:
        max-idle: 500
        max-wait: -1ms
        max-active: 8
        min-idle: 0
    lettuce:
      shutdown-timeout: 0ms
    host: 127.0.0.1
    port: 6379
    password: sirbox.cn

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


